package com.johnny.webservice.client.cxf.datatype1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2016-09-07T20:22:36.134+08:00
 * Generated source version: 2.5.9
 * 
 */
@WebService(targetNamespace = "http://cxfimp2.webservice.johnny.com/", name = "DataTypeWS")
@XmlSeeAlso({ObjectFactory.class})
public interface DataTypeWS {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getStudentsByPrice", targetNamespace = "http://cxfimp2.webservice.johnny.com/", className = "com.johnny.webservice.client.cxf.datatype1.GetStudentsByPrice")
    @WebMethod
    @ResponseWrapper(localName = "getStudentsByPriceResponse", targetNamespace = "http://cxfimp2.webservice.johnny.com/", className = "com.johnny.webservice.client.cxf.datatype1.GetStudentsByPriceResponse")
    public java.util.List<com.johnny.webservice.client.cxf.datatype1.Student> getStudentsByPrice(
        @WebParam(name = "price", targetNamespace = "")
        float price
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "addStudent", targetNamespace = "http://cxfimp2.webservice.johnny.com/", className = "com.johnny.webservice.client.cxf.datatype1.AddStudent")
    @WebMethod
    @ResponseWrapper(localName = "addStudentResponse", targetNamespace = "http://cxfimp2.webservice.johnny.com/", className = "com.johnny.webservice.client.cxf.datatype1.AddStudentResponse")
    public boolean addStudent(
        @WebParam(name = "student", targetNamespace = "")
        com.johnny.webservice.client.cxf.datatype1.Student student
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getAllStudentsMap", targetNamespace = "http://cxfimp2.webservice.johnny.com/", className = "com.johnny.webservice.client.cxf.datatype1.GetAllStudentsMap")
    @WebMethod
    @ResponseWrapper(localName = "getAllStudentsMapResponse", targetNamespace = "http://cxfimp2.webservice.johnny.com/", className = "com.johnny.webservice.client.cxf.datatype1.GetAllStudentsMapResponse")
    public com.johnny.webservice.client.cxf.datatype1.GetAllStudentsMapResponse.Result getAllStudentsMap();

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getStudentById", targetNamespace = "http://cxfimp2.webservice.johnny.com/", className = "com.johnny.webservice.client.cxf.datatype1.GetStudentById")
    @WebMethod
    @ResponseWrapper(localName = "getStudentByIdResponse", targetNamespace = "http://cxfimp2.webservice.johnny.com/", className = "com.johnny.webservice.client.cxf.datatype1.GetStudentByIdResponse")
    public com.johnny.webservice.client.cxf.datatype1.Student getStudentById(
        @WebParam(name = "id", targetNamespace = "")
        int id
    );
}
