
package com.johnny.webservice.client.jdkimpl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWSImpl", targetNamespace = "http://jdkimp.webservice.johnny.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWSImpl {


    /**
     * 
     * @param jName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "jResult", targetNamespace = "")
    @RequestWrapper(localName = "doHello", targetNamespace = "http://jdkimp.webservice.johnny.com/", className = "com.johnny.webservice.client.jdkimpl.DoHello")
    @ResponseWrapper(localName = "doHelloResponse", targetNamespace = "http://jdkimp.webservice.johnny.com/", className = "com.johnny.webservice.client.jdkimpl.DoHelloResponse")
    @Action(input = "http://jdkimp.webservice.johnny.com/HelloWSImpl/doHelloRequest", output = "http://jdkimp.webservice.johnny.com/HelloWSImpl/doHelloResponse")
    public String doHello(
        @WebParam(name = "jName", targetNamespace = "")
        String jName);

}
