package com.johnny.webservice.client.cxfimpl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2016-09-05T20:18:50.398+08:00
 * Generated source version: 2.5.9
 * 
 */
@WebService(targetNamespace = "http://cxfimp.webservice.johnny.com/", name = "HelloWS")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWS {

    @WebResult(name = "jResult", targetNamespace = "")
    @RequestWrapper(localName = "doHello", targetNamespace = "http://cxfimp.webservice.johnny.com/", className = "com.johnny.webservice.client.cxfimpl.DoHello")
    @WebMethod
    @ResponseWrapper(localName = "doHelloResponse", targetNamespace = "http://cxfimp.webservice.johnny.com/", className = "com.johnny.webservice.client.cxfimpl.DoHelloResponse")
    public java.lang.String doHello(
        @WebParam(name = "jName", targetNamespace = "")
        java.lang.String jName
    );
}
